In [21]:
# 1.Create a list of 5 integers. 
# Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

a=[2,3,4,5,6]
a.append(7)
print(a)
a.extend([2,3])
print(a)
a.insert(2,99)
print(a)
a.remove(99)
print(a)
a.pop(1)
print(a)
print(a.count(2))
print(a.index(7))
a.sort()
print(a)

a.reverse()
print(a)
a.clear()
print(a)


[2, 3, 4, 5, 6, 7]
[2, 3, 4, 5, 6, 7, 2, 3]
[2, 3, 99, 4, 5, 6, 7, 2, 3]
[2, 3, 4, 5, 6, 7, 2, 3]
[2, 4, 5, 6, 7, 2, 3]
2
4
[2, 2, 3, 4, 5, 6, 7]
[7, 6, 5, 4, 3, 2, 2]
[]


In [26]:
# 2.Create a tuple that stores 3 student names. 
# Try changing the second name in the tuple. What happens? Explain why.
a=("ram","bhim","som")
print(a)

a[1] = "lam"
print(a)
a.insert("lam",1)
print(a)


# here error is coming
# in python tuple is immutable


('ram', 'bhim', 'som')


TypeError: 'tuple' object does not support item assignment

In [29]:
# 3.Create a set of integers with some duplicate values. Print the set and explain the output.

a=[1,2,3,4,4]
print(a)
b=set(a)
print(b)
c={2,2}
print(c)

# in list u can enter duplicates
# in sets only original values

[1, 2, 3, 4, 4]
{1, 2, 3, 4}
{2}


In [36]:
# 4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
a={"name":"anu","age":23,"city":"america"}
print(a)
a["age"]=16
print(a)
a["email"] ="anu@yahoo.com"
print(a)

{'name': 'anu', 'age': 23, 'city': 'america'}
{'name': 'anu', 'age': 16, 'city': 'america'}
{'name': 'anu', 'age': 16, 'city': 'america', 'email': 'anu@yahoo.com'}


In [39]:
# Write a script that checks if a person is eligible to vote (age ≥ 18). 
# Take age as a variable and print the appropriate message
a=18
b=int(input("Enter ur age: " ))
if b>=18:
      print("u can vote")
else:
      print("u cant vote")



Enter ur age:  33


u can vote


In [40]:
# 6.Given a 'marks' variable, print the grade:
# - 90 and above: 'A'
# - 75–89: 'B'
# - 50–74: 'C'
# - Below 50: 'Fail'
a=int(input("Enter the marks: "))
if a>=90:
    print("ur grade is A")
elif a>=75:
    print("ur grade is B")
elif a>=50:
    print("ur grade is C")
else:
    print("ur fail")

Enter the marks:  44


ur fail


In [41]:
# 7.Given a number, check if it's positive, and if it is also even. 
# If not positive, print if it's zero or negative.
a=int(input("Enter a number: "))
if a>0 and a%2==0:
    print("It's a positive number and even.")
elif a>0:
    print("It's a positive number.")
elif a==0:
    print("Your given number is 0.")
else:
    print("It's a negative number.")


Enter a number:  0


Your given number is 0.


In [43]:
# 8.Create:
# - A scalar using np.array(5)
# - A 1D array with values 1 to 5
# - A 2D array (2x3) with values from 10 to 60 in steps of 10
import numpy as np
a=np.array(5)
print(a)
b=np.array([1,2,3,4,5])
print(b)
c=list(range(10,70,10))
d=np.array(c).reshape(2,3)
print(d)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [3]:
# 9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
import numpy as np
a=np.random.randint(1,101,size=(4,4))
print(a)

[[14  7 16 87]
 [34 10 15 28]
 [39 79 43 44]
 [22  7  6 51]]


In [5]:
# 10.Create a 2D numpy array of shape (3x3).
# Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
import pandas as pd
import numpy as np
a=np.random.randint(1,101,size=(3,3))
print(a)
df=pd.DataFrame(a,columns=["A","B","C"])
print(df)

[[ 1 95 55]
 [30 11  5]
 [19 42  2]]
    A   B   C
0   1  95  55
1  30  11   5
2  19  42   2


In [ ]:
# Section C: Exploring Pandas
# 11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
# - Use .info(), .describe()
# - Select 'Name' and 'City' columns
# - Drop 'City' column
# - Fill any missing values in 'Salary' column with the mean
# - Remove any duplicate rows


In [17]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Alice'],
    'Age': [25, 30, 35, 40, 22, 28, 45, 32, 29, 25],
    'City': ['NY', 'LA', 'CHI', 'HOU', 'PHX', 'PHL', 'SAT', 'SDG', 'DAL', 'NY'],
    'Salary': [50000, 60000, 70000, np.nan, 55000, 65000, 80000, 72000, 58000, 50000] 
}

df = pd.DataFrame(data)
df

,Name,Age,City,Salary
0,Alice,25,NY,50000.0
1,Bob,30,LA,60000.0
2,Charlie,35,CHI,70000.0
3,David,40,HOU,NaN
4,Eve,22,PHX,55000.0
5,Frank,28,PHL,65000.0
6,Grace,45,SAT,80000.0
7,Heidi,32,SDG,72000.0
8,Ivan,29,DAL,58000.0
9,Alice,25,NY,50000.0


In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [19]:
df.describe()

,Age,Salary
count,10.000000,9.000000
mean,31.100000,62222.222222
std,7.156194,10329.300288
min,22.000000,50000.000000
25%,25.750000,55000.000000
50%,29.500000,60000.000000
75%,34.250000,70000.000000
max,45.000000,80000.000000


In [20]:
df.columns

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

In [21]:
df[["City","Name"]]

,City,Name
0,NY,Alice
1,LA,Bob
2,CHI,Charlie
3,HOU,David
4,PHX,Eve
5,PHL,Frank
6,SAT,Grace
7,SDG,Heidi
8,DAL,Ivan
9,NY,Alice


In [22]:
df.drop(columns=['City'])

,Name,Age,Salary
0,Alice,25,50000.0
1,Bob,30,60000.0
2,Charlie,35,70000.0
3,David,40,NaN
4,Eve,22,55000.0
5,Frank,28,65000.0
6,Grace,45,80000.0
7,Heidi,32,72000.0
8,Ivan,29,58000.0
9,Alice,25,50000.0


In [24]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df

,Name,Age,City,Salary
0,Alice,25,NY,50000.000000
1,Bob,30,LA,60000.000000
2,Charlie,35,CHI,70000.000000
3,David,40,HOU,62222.222222
4,Eve,22,PHX,55000.000000
5,Frank,28,PHL,65000.000000
6,Grace,45,SAT,80000.000000
7,Heidi,32,SDG,72000.000000
8,Ivan,29,DAL,58000.000000
9,Alice,25,NY,50000.000000


In [26]:
df.drop_duplicates()


,Name,Age,City,Salary
0,Alice,25,NY,50000.000000
1,Bob,30,LA,60000.000000
2,Charlie,35,CHI,70000.000000
3,David,40,HOU,62222.222222
4,Eve,22,PHX,55000.000000
5,Frank,28,PHL,65000.000000
6,Grace,45,SAT,80000.000000
7,Heidi,32,SDG,72000.000000
8,Ivan,29,DAL,58000.000000
